services:
  postgres:
    image: postgres:15
    container_name: backend_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: offerhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    container_name: backend_postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://admin:admin@postgres:5432/offerhub
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  hasura:
    image: hasura/graphql-engine:v2.40.0
    container_name: backend_hasura
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@postgres:5432/offerhub
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: {}
